image: node:16-alpine

stages:
  - update-service

deploy:
  stage: update-service
  only:
    - main
  script:
    - npm install -g @chabokan.net/cli
    - export CHABOK_API_URL=https://apihub2.chabokan.net/fa/api/v1/
    - chabok login -t $CHABOKAN_TOKEN
    - chabok deploy -s develop
